//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livros
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public string autor { get; set; }
        public string editora { get; set; }
        public int ano { get; set; }
        public int edicao { get; set; }
        public double preco { get; set; }
        public string sinopse { get; set; }
    }
}
